### ISSUE TITLE
acbuild copy does not consider targets ending in / as directories

### ISSUE THREAD

**Issue by sharhalakis** [containers/build#201]
It seems that "acbuild copy" does not consider a target path as a directory when it ends with / and thus the following two exhibit different behavior:

```
acbuild copy file /path/to/
acbuild copy file /path/to/file
```

The first one acts just like `acbuild copy file /path/to`

It seems that the problem happens because of this in lib/copy.go:CopyToTarget():

```
target := path.Join(a.CurrentACIPath, aci.RootfsDir, to)
```

since Join() removes any trailing / which then causes the subsequent path.Split() to return the last directory as a file.

**Comment by dgonyeo** [comment]
Right now the semantics around `acbuild copy` are weird.

acbuild only fetches dependencies when `acbuild run` is used, and thus when an `acbuild copy` command is used acbuild can't tell when a target path is a preexisting directory. If you do `acbuild copy myapp /usr/bin`, and `/usr/bin` is coming from a dependency, acbuild can't tell if you really want your binary to exist at `/usr/bin` or if you want the binary exist at `/usr/bin/myapp`. So it forces you to type out the full path, instead of just the destination directory.

To try to make this a little clearer, in the next release `acbuild copy` is being split out into `acbuild copy` and `acbuild copy-to-dir`. So the following two commands will be equivalent:

```
acbuild copy-to-dir file /path/to
acbuild copy file /path/to/file
```

The UX for this would be far better if acbuild just preemptively fetched dependencies, and thus could know if `/path/to` exists, but right now acbuild doesn't hold on to dependencies between builds, and pulling down potentially 100s of megabytes per build you didn't need to just so you can copy a file into a tarball feels silly. It doesn't hold on to dependencies because I didn't have a lot of confidence in acbuild's dependency logic when I first wrote it, but it's been in the wild now without any issues I've heard of, so it'll probably be time to make that change soon.

So back to your suggestion: I'd prefer to not have acbuild's behavior vary based on a trailing slash, since that's something that could be inserted by shell tab completion without the user thinking much about it. I think a better path forward is for acbuild to preemptively fetch dependencies and store them between builds, such that acbuild can know when a target is a preexisting directory and act accordingly.

**Comment by sharhalakis** [comment]
This makes sense, so I suggest treating a trailing / as an error when doing copy-as-file operations because this will always be a bug. I don't think there will ever be a legitimate case of saying: `acbuild copy file /path/to/file/` to actually mean `acbuild copy file /path/to/file`, and it will just be more things to troubleshoot.

An error message pointing to the "copy-to-dir" command when a trailing slash is detected in a "copy" command should be adequate.

Alternatively, you could take advantage of the trailing slash and merge copy and copy-to-dir to make them treat a trailing / as "copy-to-dir", which may be more intuitive. In that case, if the inventory problem is sorted out in the future, there will be no required changes in the user aspect of the commands.

**Comment by sanmai-NL** [comment]
@dgonyeo: this issue is quite annoying, to me at least. When will @sharhalakis’ suggestion be considered?

**Comment by dgonyeo** [comment]
His suggestions sounds very reasonable to me. I'm not sure about merging the two commands, but erroring on trailing slashes should be fine.

I unfortunately don't really have much spare time to work on this project these days, but if you can come up with a patch I'd be happy to review it.
