### ISSUE TITLE
ERROR: ACName must contain only lower case alphanumeric characters plus "-"

### ISSUE THREAD

**Issue by DJviolin** [containers/build#282]
I'm getting this errror:

```
Adding mount point "/var/lib/container/rkt/debian"="/mnt"
mount add: ACName must contain only lower case alphanumeric characters plus "-"
```

From this commands:

```sh
$ acbuild --debug mount add $(pwd) /mnt
# or
$ acbuild --debug mount add . /mnt
```

System info:

```sh
$ acbuild version
acbuild version v0.4.0
appc version 0.8.5
$ uname -a
Linux debian 4.8.0-0.bpo.2-amd64 #1 SMP Debian 4.8.11-1~bpo8+1 (2016-12-14) x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.6 (jessie)
Release:        8.6
Codename:       jessie
```

**Comment by jonboulle** [comment]
The "mount" concept in ACIs is a bit different from what you might be used to with Docker volumes; basically rather than a `sourcePath -> destPath` mapping, it's instead a `name -> destPath` mapping where the `name` is an index into a set of _volumes_ that the running pod is configured with. (The idea being that the specific source-path on the host is really a runtime parameter rather than something you want to predetermine at build time).

This is explained with some relevant examples in the rkt documentation: https://coreos.com/rkt/docs/latest/subcommands/run.html#mounting-volumes

So in your particular example you might want something like:
```
acbuild mount add my-debian-vol mnt`
<write the image>
rkt run --volume my-debian-vol,kind=host 
```

(Or you could just skip adding the mount to the ACI at all during the build, and just specify it during the running of the image.)

Does that help?

**Comment by DJviolin** [comment]
Thank You! That's clearing things out.

So I have to write something like this?

```
$ acbuild --debug mount add my-named-vol /mnt
$ rkt run --volume my-named-vol,kind=host,source=$(pwd),readOnly=true debian.aci
```

**Comment by jonboulle** [comment]
Yep, exactly!
