### ISSUE TITLE
script: ending the build results in "no build in progress"

### ISSUE THREAD

**Issue by lucab** [containers/build#288]
I'm using an simple acbuild-script to copy a bunch of files and write an ACI for a small experiment of mine.

Script source is [here](https://github.com/lucab/rkt-volo/blob/master/dist/stage1-volo.acbuild) on github. It works generally fine, except that ending the build errors out:
```
Writing ACI to target/stage1-volo.aci
Ending the build
script: no build in progress in this working dir - try "acbuild begin"
exit status 1
```

The resulting aci file however is completely fine. Not a big deal, mostly a cosmetic annoyance.

**Comment by dgonyeo** [comment]
Script mode in acbuild will handle calling end for you. What I believe happens here is that your end gets called and completes successfully, and then acbuild calls end because the script is over, and the second one fails.

I'll make acbuild emit some warning explaining this when you use end in a script.

**Comment by lucab** [comment]
You seems to be right in that, the "end" at the bottom is superfluous.

**Comment by dgonyeo** [comment]
The reason I had acbuild do `end` for you in this instance is to remove this boilerplate from pretty much every acbuild bash script:
```
acbuildEnd() {
    export EXIT=$?
    acbuild --debug end && exit $EXIT 
}
trap acbuildEnd EXIT
```
